name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flask
        run: pip install flask

      - name: Start Flask App
        run: |
          nohup python app.py &
          sleep 15

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            --network="host" \
            owasp/zap2docker-stable \
            zap-baseline.py -t http://localhost:5050 -r zap-report.html

      - name: Security Gate
        run: |
          if grep -E "High|Medium" zap-report.html; then
            echo "❌ Vulnerabilities found!"
            exit 1
          else
            echo "✅ Secure build"
          fi
